### ISSUE TITLE
Custom scheduling not visible in the GUI

### ISSUE THREAD

**Issue by aborruso** [githubocto/flat-editor#10]
I have set a [custom scheduling](https://github.com/aborruso/flat_data_bash_example/blob/main/.github/workflows/flat.yml) and it's not visible in the GUI, the rado button is not checked.

![flat](https://user-images.githubusercontent.com/30607/119091698-bfca9d00-ba0d-11eb-9521-95d37f024464.gif)

**Comment by mattrothenberg** [comment]
Published in https://github.com/githubocto/flat-editor/commit/fa66ec8f9b10002cef1fc8c7983fd40fa77e4ff9
