### ISSUE TITLE
Cronjob for every minute appears to be every 5 minutes

### ISSUE THREAD

**Issue by jobedylbas** [githubocto/flat-editor#15]
I don't if it is an issue, but when I write "* * * * *", the message shown is "Will run: every 5 minutes" but should be "every minute".

<img width="515" alt="Screen Shot 2021-06-21 at 08 38 57" src="https://user-images.githubusercontent.com/13896705/122755958-20970080-d26c-11eb-86dd-3c8c941f34f5.png">

**Comment by jamesa** [comment]
That's a limitation of GitHub actions. Per [these docs](https://docs.github.com/en/actions/reference/events-that-trigger-workflows#schedule):
> "The shortest interval you can run scheduled workflows is once every 5 minutes."
