### ISSUE TITLE
Does not load after init

### ISSUE THREAD

**Issue by johlym** [githubocto/flat-editor#20]
Sort of a follow-on from #9, but I figured I'd open my own Issue so as to not blow up others' inboxes unnecessarily. I'm seeing similar behavior, except I'm getting 

> Please ensure you're working out of a Git repository with a valid upstream remote set.

Though that is very much the case. The Output and Problems tabs are empty. 

I get this in the VSCode dev tools console every time I click "Refresh":

![CleanShot 2022-02-03 at 17 54 15@2x](https://user-images.githubusercontent.com/5686227/152459618-e47f71ea-435f-4210-b252-bfb2d37417d9.jpg)

(I've clicked Refresh 11 times so far 😅)

ETA: I'm running 0.23.0

Thoughts?

**Comment by mattrothenberg** [comment]
Hi @johlym!

Would you be able to share the Git repository that you're working out of, assuming it's public?

**Comment by mattrothenberg** [comment]
Here are the steps that I'm following as I try to reproduce this issue on my end.

From the command line, I create a directory and initialize a Git repository with an upstream remote.
```bash
mkdir flat-test
cd flat-test
git init
git remote add origin <your-remote-goes-here>
code .
```

Once I've opened in Visual Studio Code, I run **Initialize Flat YML file** from the command palette.

![Screen Shot 2022-02-08 at 10 31 32 AM](https://user-images.githubusercontent.com/5148596/153019972-74267fcb-6aee-4e71-a86b-04f440d2ad31.png)
 
I confirm that the UI is visible and interactive 
![Screen Shot 2022-02-08 at 10 32 05 AM](https://user-images.githubusercontent.com/5148596/153020089-78587a00-9db8-425d-b76c-31d548335b2d.png)

**Comment by johlym** [comment]
Feel free to take a look: https://github.com/johlym/johnathan-org

Trying init with an empty, freshly init-ed repo and it worked: 
![CleanShot 2022-02-08 at 09 36 07@2x](https://user-images.githubusercontent.com/5686227/153043731-4b932c58-bcba-496e-9fe0-5b8cf49f6a2b.jpg)

Going back to my original repo, it now seems to work fine, though nothing about my repo has changed. 

![CleanShot 2022-02-08 at 09 37 21@2x](https://user-images.githubusercontent.com/5686227/153043961-9c48e4f7-e0f5-4367-9c1c-f4b8ea73ec49.jpg)

**Comment by mattrothenberg** [comment]
@johlym Curious! I'm glad it's working for you now, though :)

Flat Editor does some hackery internally to hook into VSCode's Git extension in order to figure out what repository you're working out of. I wonder if, when you were testing initially, somehow the Git extension wasn't activated, or perhaps you were working out of a different workspace?

**Comment by johlym** [comment]
Not that I'm aware of, though I also don't use Workspaces, explicitly (just the "Open Folder"-and-peel-out method). 

Either way, I'll holler if it comes up, again. Cheers!
