### ISSUE TITLE
Editor does not load

### ISSUE THREAD

**Issue by gnatih** [githubocto/flat-editor#23]
This is the exact same issue as #20, but I haven't been able to get it working yet.

I keep getting the `Please ensure you're working out of a Git repository with a valid upstream remote set.` message, with all the test-repos, with a `Refresh` button. Nothing happens when you click refresh.

Steps I've tried:

1. Tried with a fresh git init-ed repository
2. Re-installed the extension several times
3. Re-installed vs-code too.

**Comment by alecglen** [comment]
Same issue here.

**Comment by mattrothenberg** [comment]
Apologies for the issue, y'all! I have a fix in the works #24

**Comment by mattrothenberg** [comment]
This should be fixed in version `0.24.0`.

Please re-open another issue if the problem persists!

**Comment by gnatih** [comment]
Thank you for fixing this. I can confirm that the editor works with `0.24.0`.

**Comment by alecglen** [comment]
Same here!
